[build]
  publish = ".next"
  command = "npm run build"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ."

[build.environment]
  NODE_VERSION = "20"
  NODE_ENV = "production"
  NPM_FLAGS = "--production=false"

[functions]
  node_bundler = "esbuild"
